### ISSUE TITLE
Fix animation from Search to Single (no animation) and remove navigator

### ISSUE THREAD

**Issue by jacqouese** [MASSHUU12/bookapp#36]

**Comment by jacqouese** [comment]
![Image](https://user-images.githubusercontent.com/74781614/196494301-22324ada-3bee-4c79-8860-c8ef11d0a0c1.png)

**Comment by MASSHUU12** [comment]
It's not that easy, it would require rewriting the entire router

**Comment by jacqouese** [comment]
![Image](https://user-images.githubusercontent.com/74781614/196725159-a88ed8ef-5117-4465-83b6-f53a429271c2.gif)
